const fs = require("fs");
const path = require("path");
const { getProviderStatus } = require("../scripts/ai-runner-lib");
const { parseRunnerJson } = require("./utils");
const { createRunnerHealthTracker } = require("./runner-health");

function createAiAdapter(options) {
  const {
    name,
    envRunnerScript,
    envAllowFallback,
    defaultOpenAiRunner,
    defaultCodexRunner,
    promptVersion,
    skillPath,
    downstreamSkill,
    fallbackKey = null,
    fallbackSource = "backend-fallback",
    getExtraRunnerConfig = () => ({}),
    getExtraStaticStatus = () => ({}),
    timeoutMs = 120000,
  } = options;

  function getRunnerConfig() {
    const providerStatus = getProviderStatus();
    const isCodexCustom = providerStatus.mode === "codex-cli" && providerStatus.codexUsesCustomProvider;
    return {
      providerStatus,
      runner: process.env[envRunnerScript] || (providerStatus.mode === "openai-compatible" ? defaultOpenAiRunner : defaultCodexRunner),
      allowFallback: process.env[envAllowFallback] === "1",
      timeoutMs: isCodexCustom ? 45 * 1000 : timeoutMs,
      preferFastFallback: isCodexCustom,
      ...getExtraRunnerConfig(providerStatus),
    };
  }

  function getStaticRunnerStatus() {
    const runnerConfig = getRunnerConfig();
    return {
      configured: Boolean(runnerConfig.runner),
      runnerScript: runnerConfig.runner,
      runnerScriptExists: Boolean(runnerConfig.runner && fs.existsSync(path.resolve(process.cwd(), runnerConfig.runner))),
      provider: runnerConfig.providerStatus.provider,
      mode: runnerConfig.providerStatus.mode,
      providerMode: runnerConfig.providerStatus.mode,
      model: runnerConfig.providerStatus.model || "",
      allowFallback: runnerConfig.allowFallback,
      apiKeyConfigured: runnerConfig.providerStatus.apiKeyConfigured,
      baseUrlConfigured: runnerConfig.providerStatus.baseUrlConfigured,
      codexRunnable: runnerConfig.providerStatus.codexRunnable,
      codexDetail: runnerConfig.providerStatus.codexDetail || "",
      promptVersion,
      skillPath,
      downstreamSkill,
      ...getExtraStaticStatus(runnerConfig),
    };
  }

  const runnerHealth = createRunnerHealthTracker(name, getStaticRunnerStatus);

  function getRunnerStatus() {
    return runnerHealth.getStatus();
  }

  function runConfiguredCommand(request, runnerConfig = getRunnerConfig()) {
    return new Promise((resolve, reject) => {
      const { execFile } = require("child_process");
      const runnerPath = path.resolve(process.cwd(), runnerConfig.runner);
      const child = execFile(process.execPath, [runnerPath], { maxBuffer: 20 * 1024 * 1024, timeout: runnerConfig.timeoutMs || timeoutMs }, (error, stdout, stderr) => {
        if (error) {
          reject(new Error(`${error.message}\n${stderr || ""}`.trim()));
          return;
        }
        try {
          resolve({
            ok: true,
            source: path.basename(runnerConfig.runner),
            promptVersion,
            skillPath,
            downstreamSkill,
            ...parseRunnerJson(stdout),
          });
        } catch (parseError) {
          reject(parseError);
        }
      });
      if (child.stdin && typeof child.stdin.on === "function") child.stdin.on("error", () => {});
      child.stdin.write(JSON.stringify(request, null, 2));
      child.stdin.end();
    });
  }

  function runWithFallback(request, runConfiguredFn, buildFallbackFn) {
    const runnerConfig = getRunnerConfig();
    const startedAt = Date.now();
    runnerHealth.startRun();
    return runConfiguredFn(request, runnerConfig).catch((error) => {
      if (!runnerConfig.allowFallback) {
        runnerHealth.markFailure({
          error: error.message || String(error),
          durationMs: Date.now() - startedAt,
          source: path.basename(runnerConfig.runner || ""),
        });
        throw new Error(`${name} failed: ${error.message || String(error)}`);
      }
      const fallbackResult = buildFallbackFn(request);
      const result = {
        ok: true,
        source: fallbackSource,
        fallbackReason: error.message || String(error),
        fallbackWarning: "Result was generated by local fallback and was not confirmed by the AI backend.",
        promptVersion,
        skillPath,
        downstreamSkill,
        ...(fallbackKey ? { [fallbackKey]: fallbackResult } : fallbackResult),
      };
      runnerHealth.markFallback({
        error: error.message || String(error),
        fallbackReason: result.fallbackReason,
        durationMs: Date.now() - startedAt,
        source: result.source,
      });
      return result;
    }).then((result) => {
      if (result?.source !== fallbackSource) {
        runnerHealth.markSuccess({
          durationMs: Date.now() - startedAt,
          source: result?.source || path.basename(runnerConfig.runner || ""),
        });
      }
      return result;
    });
  }

  return {
    getRunnerConfig,
    getStaticRunnerStatus,
    getRunnerStatus,
    runConfiguredCommand,
    runWithFallback,
    _resetRunnerStatusForTesting: () => runnerHealth.resetForTesting(),
  };
}

module.exports = { createAiAdapter };
