/**
 * Storage facade — delegates to SQLite backend.
 * Keeps exact same exports as before so callers need zero changes.
 */
const sqlite = require("./store-sqlite");

module.exports = {
  readDb: sqlite.readDb,
  writeDb: sqlite.writeDb,
  replaceDb: sqlite.replaceDb,
  upsertContract: sqlite.upsertContract,
  upsertContractWithAudit: sqlite.upsertContractWithAudit,
  upsertContractVersion: sqlite.upsertContractVersion,
  upsertContractVersionWithAudit: sqlite.upsertContractVersionWithAudit,
  replaceContractClauses: sqlite.replaceContractClauses,
  replaceContractFindings: sqlite.replaceContractFindings,
  replaceClauseActions: sqlite.replaceClauseActions,
  appendInsertedClause: sqlite.appendInsertedClause,
  patchAuxState: sqlite.patchAuxState,
  appendAuditLog: sqlite.appendAuditLog,
  saveAnalysisJob: sqlite.saveAnalysisJob,
  listAnalysisJobs: sqlite.listAnalysisJobs,
  deleteAnalysisJob: sqlite.deleteAnalysisJob,
  deleteContractCascade: sqlite.deleteContractCascade,
  deleteContractVersionCascade: sqlite.deleteContractVersionCascade,
  saveFile: sqlite.saveFile,
  flattenClauseActions: sqlite.flattenClauseActions,
  saveContractFile: sqlite.saveContractFile,
  getContractFiles: sqlite.getContractFiles,
  getFileById: sqlite.getFileById,
  deleteFile: sqlite.deleteFile,
  getContractFolder: sqlite.getContractFolder,
  getContractWithTexts: sqlite.getContractWithTexts,
  listAllContractsWithPaths: sqlite.listAllContractsWithPaths,
  runAutoBackup: sqlite.runAutoBackup,
  runWalCheckpoint: sqlite.runWalCheckpoint,
  checkpointIfWalLarge: sqlite.checkpointIfWalLarge,
  restoreBackupToDirectory: sqlite.restoreBackupToDirectory,
  search: sqlite.search,
  searchContracts: sqlite.searchContracts,
  searchClauses: sqlite.searchClauses,
  searchGlobal: sqlite.searchGlobal,
  DATA_DIR: sqlite.DATA_DIR,
  DB_PATH: sqlite.DB_PATH,
  WAL_PATH: sqlite.WAL_PATH,
  FILE_DIR: sqlite.FILE_DIR,
  WORKBENCH_ROOT: sqlite.WORKBENCH_ROOT,
};
